export const ProjectFilterList = [
  {
    label: "Show All",
    value: "",
  },
  {
    label: "Show Favorite",
    value: "",
  },
  {
    label: "Show On Hold",
    value: "",
  },
  {
    label: "Show Open",
    value: "",
  },
  {
    label: "Show Closed",
    value: "",
  },
  {
    label: "Show Invoiced",
    value: "",
  },
];

export const ProjectCardListSelect = [
  "open",
  "Manage",
  "Insights",
  "Download",
  "Set Up",
  "Dispose",
];

export const ProjectData = [
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
  {
    projectName: "Project Name",
    projectCode: "Code",
    manager: "Manager",
    client: "12345 Research Ltd.",
    LOI: "[hh:mm:ss]",
    Invite: "123,456|65,789",
    Completed: "521/600",
    Incidence: "15%/20%",
  },
];
